### PR TITLE
DIG-1743: Stable candidate v5.0.0

### PR DESCRIPTION
**Pull request by daisieh**
I can't figure out how to make this PR without all of the old commits and whatnot.

## Highlights
Clinical Data Model v3.1
Basic centralized logging
Access logs - decision logging in opa
Site curator role in opa
Confident in CanDIG meeting performance needs 
Gunicorn
Not available added to ‘incomplete’ statistics
Updated documentation for production and ingest

### CODE REVIEW

**Review by SonQBChau — APPROVED** [review]
LGTM!

**Review by OrdiNeu — APPROVED** [review]
Works on my machine. Great job everyone!

**Review by mshadbolt — APPROVED** [review]
works for me

**Review by CourtneyGosselin — APPROVED** [review]
LGTM! Works on BCGSC-DEV

**Pull request merged**
