### PR TITLE
DIG-1372: Query can assemble discovery queries

### PR DESCRIPTION
**Pull request by OrdiNeu**
## Ticket(s)

- [DIG-1372: Query can assemble discovery queries](https://candig.atlassian.net/browse/DIG-1372)

## Description

- This changes the behaviour of the summary statistics by grabbing their counts from the new Query endpoint (located [here](https://github.com/CanDIG/candigv2-query/pull/28)), and shows summary statistics even for unauthorized cohorts:

Screenshot from 2024-04-12 15-36-47

Here, the logged in user has no access to the TEST-2 user, but the numbers still add up to 5 donors. This further fixes the patient counts for donors in cohorts you do not have access to, and properly shows the Request Access button properly.

### CODE REVIEW

**Comment by daisieh** [comment]
I don't often review data portal PRs...what is the testing procedure for this?

**Comment by OrdiNeu** [comment]
Normally we run through parts of the [Frontend Testing Runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) to make sure it's all still there. In this case it's mostly just loading up data and seeing if the counts display what you'd expefct.

**Comment by OrdiNeu** [comment]
Just rebased it to get rid of the merge conflicts

**Review by daisieh — APPROVED** [review]
Loads correctly and looks as expected.

**Comment by mshadbolt** [comment]
fix merge conflicts by updating query and data portal to latest develop commits

**Pull request merged**
