### PR TITLE
DIG-1275: modifying site roles

### PR DESCRIPTION
**Pull request by daisieh**
Picks up changes in https://github.com/CanDIG/candigv2-ingest/pull/86 and the matching permissions changes needed for vault-setup and ingest's docker-compose. Also implements tests for roles.

### CODE REVIEW

**Review by OrdiNeu — COMMENTED** [review]
Maybe we should add an integration test for the new ingest endpoints? (is_user_in_role, add/remove roles?)

**Comment by daisieh** [comment]
I did, in https://github.com/CanDIG/CanDIGv2/commit/01d9facf1b079b13ff0864841538e62c48d0c3c4

**Comment by daisieh** [comment]
Or do you mean for all of them?

**Comment by OrdiNeu** [comment]
Oh, I saw the site admin check and assumed that was only checking site admin without going through the new `is_user_in_role` endpoint. I do see the add/remove role test now :+1:

**Review by OrdiNeu — APPROVED** [review]
LGTM :heavy_check_mark:

**Pull request merged**
