### PR TITLE
update chord-metadata to use secrets file for password

### PR DESCRIPTION
**Pull request by daisieh**
Also snuck in a typo fix for the docker-compose context

### CODE REVIEW

**Comment by daisieh** [comment]
If you want, I can wait until after you approve the submodule's PR https://github.com/CanDIG/katsu/pull/32 and then update its commit in this PR.

**Comment by daisieh** [comment]
Decided that the shared volume thing is a different thing entirely, so I took those changes out.

**Review by shaikh-rashid — APPROVED** [review]
Thank you for solving this bug!

**Comment by shaikh-rashid** [comment]
Please wait to merge this PR. We need to discuss a merge strategy as we have multiple outstanding PRs in place.

**Pull request merged**
