### PR TITLE
initial commit of new auth middleware

### PR DESCRIPTION
**Pull request by jimmyhli**
Edit by @amanjeev on Jan 31 2022:  Aman will pull this middleware into his branch and open a new PR.  At the time of opening new PR this one will be closed without merging.

PR that supersedes/will supersede  this https://github.com/CanDIG/CanDIGv2/pull/112

### CODE REVIEW

**Review by shaikh-rashid — COMMENTED** [review]
LGTM, but I have added other reviewers who may provide better insight into this than I can.

**Review by daisieh — APPROVED** [review]
It looks good to me as well.

**Review by ljdursi — APPROVED** [review]

**Comment by amanjeev** [comment]
I am putting a soft-block on this.  @haoyuanli and I spoke a week ago and I will merge this into my own branch and open that PR after changing existing APIs to use these middlewares

**Comment by amanjeev** [comment]
Closed because #112 was merged and supersedes this.

**Pull request closed without merging**
