### PR TITLE
v4.1.0: Improved authz, queries, speedups

### PR DESCRIPTION
**Pull request by daisieh**
## v4.1.0: Improved authz, queries, speedups
NOTE: This stable release includes a major version change to Keycloak (16 -> 24), so your configuration will need to be updated to match the new configuration system.

* New authorizations for Site Roles, Programs, Users
* Discovery queries
* Speedups for data portal loading

### Data portal
* Donor timelines
* Discovery queries
* Viz tweaks

### Katsu
* Overview stats cached in redis

### Htsget
* Updated methods to use latest version of Opa/authx methods and fixed tests
* Added get_cohort_samples to htsget_operations

### Federation
* Update default timeout
* Bump authx version

### Opa
* Site roles, including site admin, now defined in Opa
* Program authorizations are defined in Opa's vault secret store
* User-specific program authorizations are defined in Opa's vault secret store
* Refactored rego policies and created unit tests

### Tyk/Vault/Keycloak/Minio
* New Keycloak version - updated to version 24.0.0
* Cleaned up Tyk templates
* Vault updates for Opa and authx updates

### Integration tests
* Tests for new User/Program authorizations
* Tests for Query

### Other changes
* Improved site admin token handling
* Warns the site administrator if the default site admin account is still active
* Nightly build setup for dev

- [x] All submodule versions have been updated in etc/env/example.env
- [x] Update .etc/env/example.env for .env CANDIG_VERSION to current release vX.X.X. The version needs to match tag for linking `https://github.com/CanDIG/CanDIGv2/releases/tag/${CANDIG_VERSION}`
- [x] Submodules point to latest stable release on each repo
- [x] Appropriate integration tests have been made to validate the changes
- [x] Passes integration tests on a development instance
- [ ] Passes [frontend runbook](https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook) testing

### CODE REVIEW

**Comment by mshadbolt** [comment]
I feel like given there are multiple breaking changes that this should be a major version jump?

**Comment by daisieh** [comment]
I think the only possible breaking change is keycloak...

**Comment by mshadbolt** [comment]
So would a CanDIG node running v4.0.0 be able to successfully federate with a CanDIG node running v4.1.0?

**Comment by daisieh** [comment]
In as much as they could do it before, sure. If a node running the new system wanted to federate with a node running the old system, the new node would see everything successfully (hopefully), but the old node would see the same bugs as before.

**Review by OrdiNeu — APPROVED** [review]
Runbook tests OK, though I noticed a discrepancy in the runbook itself (not related to this release). :heavy_check_mark:

**Review by mshadbolt — COMMENTED** [review]
I also ran through the runbook on local and passes apart from known bugs. I updated the data portal stable release as there were a couple of commits that were done while the PR was open but the release had already been made. I can re-review when the keycloak work is added to the branch.

**Comment by daisieh** [comment]
This version already has the Keycloak updates, but https://github.com/CanDIG/CanDIGv2/pull/577 does not, if you want to review that one as well.

**Comment by mshadbolt** [comment]
I meant when Son figures out the keycloak prod settings and add them to this branch

**Comment by daisieh** [comment]
Closing in favor of #577 .

**Pull request closed without merging**
