### PR TITLE
v3.0.0: Katsu UUIDs, authx with vault/opa service stores

### PR DESCRIPTION
**Pull request by daisieh**
## v3.0.0: Katsu UUIDs, authx with vault/opa service stores
* Katsu uses UUIDs
* Opa uses Vault service stores for secrets (authx v2.0.0)
* Update to Python 3.12, Alpine 3.18

### Data portal
* Katsu UUIDs, package updates

### Katsu
* UUIDs

### Htsget
* New authx, tweaks 

### Federation
* Dependency updates, authx updates 

### Opa
* Use Vault secret stores for data

### Tyk/Vault/Keycloak/Minio
* Vault secret stores

### Integration tests
* new tests for Opa ingest

### Other changes

- [x] All submodule versions have been updated in etc/env/example.env
- [x] Submodules point to latest stable release on each repo
- [x] Appropriate integration tests have been made to validate the changes
- [x] Passes integration tests on a development instance

### CODE REVIEW

**Review by OrdiNeu — APPROVED** [review]
All of the stable-candidates seem good to go from my end :heavy_check_mark:

**Comment by mshadbolt** [comment]
Did we go through the frontend runbook for this release and does it incorporate the fix for the bug where genomic data wasn't displaying in the portal?

**Comment by daisieh** [comment]
This one https://candig.atlassian.net/browse/DIG-1446? If so, no, because I based the stable release on what we'd agreed on in sprint planning on Monday. I didn't approve these fixes until after I'd already been working on the stable release and didn't realize that they should have been included.

**Comment by mshadbolt** [comment]
Yeah that's fair, the fix came later, I feel a bit weird releasing when we know there's a significant bug but hopefully we will make the next release quite quickly and recommend people wait for that one.

**Pull request merged**
