### PR TITLE
Load ingest test data from the ingest repo in stack

### PR DESCRIPTION
**Pull request by mshadbolt**
This commit loads the `clinical_ingest.json` and `genomic_ingest.json` from the currently checked out repo in the stack, rather than the develop branch of ingest.

To test:

* Run `make test-integration`.

### CODE REVIEW

**Comment by mshadbolt** [comment]
The test failures are expected because the version of clinical_ingest.json in the stack does not have date intervals but it refers to the katsu schema that does have date intervals, even though the katsu in the stack does not have date intervals. Therefore clinical ingest fails, and subsequently query can't query any clinical data.

I am not sure how or if we should fix this.

**Comment by daisieh** [comment]
I don't think that's the case: the version of clinical ingest in here includes https://github.com/CanDIG/candigv2-ingest/pull/56, which fixed the clinical_ingest.json. The failure here is now this sporadic problem we've been seeing here: https://candig.atlassian.net/browse/DIG-1479

**Review by daisieh — APPROVED** [review]
LGTM

**Comment by mshadbolt** [comment]
We will merge this anyway because the integration test failure is unrelated.

**Pull request merged**
