### PR TITLE
Add runbook check off to tasks

### PR DESCRIPTION
**Pull request by mshadbolt**
Frontend runbook should be checked off before creating a stable release

### CODE REVIEW

**Comment by daisieh** [comment]
Is there a link for the runbook?

**Comment by OrdiNeu** [comment]
Could be added as a link: https://candig.atlassian.net/wiki/spaces/CA/pages/822018050/Frontend+Testing+Runbook

**Review by daisieh — APPROVED** [review]
LGTM!

**Comment by mshadbolt** [comment]
merging despite failing checks because this change is unrelated (docs only)

**Pull request merged**
