### PR TITLE
DIG-1071: Revert "cleanup of conda related scripts that are no longer needed"

### PR DESCRIPTION
**Pull request by OrdiNeu**
This is a simple `git revert` for commit dc209a53b8b1e9289b137ab6cc03002e7a3522d7 , and a simple documentation update.

**To test**:
- The build process needs to still work (instructions on [this version of the docs](https://github.com/CanDIG/CanDIGv2/blob/9a5be2859a8209ccf24f3422a17b67f1d26b4ed8/docs/install-docker.md), but with the latest versions of each submodule. I've tested building it myself, but should be confirmed on everyone's system.

- [x] Ubuntu
- [x] MacOS X
- [x] MacOS X (M1)
- [x] Windows (WSL)

### CODE REVIEW

**Review by daisieh — APPROVED** [review]
I did a `make clean-all`, then did `make bin-conda`, `make init-docker`, `make compose`, `make init-authx`. Everything works again.

I tested basic curls for keycloak tokens, opa datasets, and htsget pytest.

**Review by SonQBChau — APPROVED** [review]
worked on M1

**Review by CourtneyGosselin — CHANGES_REQUESTED** [review]
Doesn't work on WSL systems because of the infinite symlink loop. It's an error with multiple solutions found https://github.com/conda/conda/issues/10333. What worked on my system was to install miniconda3 at ~/miniconda3 and change the makefle installation instructions to accommodate the new installation location.

**What needs to change:**
- miniconda3 must be installed at ~/miniconda3 on WSL systems to avoid infinite symlink loop ` bash bin/miniconda_install.sh -f -b -u -p ~/miniconda3`
- Makefile needs to change  env variable for WSL systems to `CONDA_BASE = ~/miniconda3`

**Comment by kcranston** [comment]
thanks, @CourtneyGosselin See also https://github.com/CanDIG/CanDIGv2/issues/174, which might solve both the WSL and the M1 problems with the current conda workflow.

**Comment by OrdiNeu** [comment]
> Doesn't work on WSL systems because of the infinite symlink loop. It's an error with multiple solutions found [conda/conda#10333](https://github.com/conda/conda/issues/10333). What worked on my system was to install miniconda3 at ~/miniconda3 and change the makefle installation instructions to accommodate the new installation location.
> 
> **What needs to change:**
> 
>     * miniconda3 must be installed at ~/miniconda3 on WSL systems to avoid infinite symlink loop ` bash bin/miniconda_install.sh -f -b -u -p ~/miniconda3`
> 
>     * Makefile needs to change  env variable for WSL systems to `CONDA_BASE = ~/miniconda3`

Thanks Courtney, I've added the `CONDA_BASE` change to the example environment, and added the warning into the `install-docker.md` documentation!

**Comment by kcranston** [comment]
I think the install location for conda also needs to change, not just `CONDA_BASE`. As it stands now, conda gets installed in a path that involves the variable `DIR` and then sourced with an unrelated path that involves `CONDA_BASE`. For me this means:

```
bash /Users/karen/Documents/candig/repos/CanDIGv2/bin/miniconda_install.sh -f -b -u -p /Users/karen/Documents/candig/repos/CanDIGv2/bin/miniconda3
```
 and then I get this output a few lines later:
 ```
 source /Users/karen/bin/miniconda3/etc/profile.d/conda.sh && /Users/karen/bin/miniconda3/bin/conda init
bash: /Users/karen/bin/miniconda3/etc/profile.d/conda.sh: No such file or directory
```
Also important to note that the install is a _force install_ so it will blow up any existing conda at that path. Warnings here would be nice.

**Review by kcranston — APPROVED** [review]
This works for me on M1, and I also added (and tested) instructions for using a local conda installation.

**Comment by kcranston** [comment]
If this now works for @CourtneyGosselin, we can merge.

**Review by CourtneyGosselin — APPROVED** [review]
Works on WSL!

**Pull request merged**
