### PR TITLE
DIG-1438: updates to make system, tweaks to vault setup

### PR DESCRIPTION
**Pull request by daisieh**
* Reordered the way we make services
* Tweaked the vault setup so that it can still run successfully, even if it's already been initialized
* Fixed the way we count expected # of containers
* Changed VAULT_SERVICE_URL to VAULT_PRIVATE_URL to match the rest of the services
* vault setup re-creates any service stores if it needs to be re-composed on its own
* Added query to a few more places it needed to be in tyk's config files

Tests should still run successfully: this PR is good if nothing breaks.

### CODE REVIEW

**Comment by mshadbolt** [comment]
Would be great to have this merged before the DevOps party tomorrow!

**Comment by daisieh** [comment]
@mshadbolt would you feel comfortable doing the code review on this?

**Comment by mshadbolt** [comment]
I feel okay about the makefile/docker compose changes but know very little about tyk and vault... but maybe no one across the team knows too much at the point anyway?
Can definitely start out by testing out the makefile changes at least

**Comment by mshadbolt** [comment]
First attempt at the new build-all and I get stuck with ingest giving me this error:
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/marionshadbolt/Documents/GitHub/CanDIGv2/tmp/secrets/keycloak-client-local_candig-secret
```
The 13 containers before this came up and are running okay as far as I can tell

Full output from candig-ingest is:
```
if [ -f lib/candig-ingest/candig-ingest_preflight.sh ]; then \
        source lib/candig-ingest/candig-ingest_preflight.sh 2>&1 | tee -a tmp/error.txt; \
        fi
export SERVICE_NAME=candig-ingest; \
        DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 \
        docker compose -f lib/candigv2/docker-compose.yml -f lib/candig-ingest/docker-compose.yml build  2>&1 | tee -a tmp/error.txt
#0 building with "desktop-linux" instance using docker driver

#1 [candig-ingest internal] load build definition from Dockerfile
#1 transferring dockerfile: 635B done
#1 DONE 0.0s

#2 [candig-ingest internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [candig-ingest internal] load metadata for docker.io/library/python:3.12
#3 DONE 0.5s

#4 [candig-ingest  1/10] FROM docker.io/library/python:3.12@sha256:7e082bf2ab924afce07aef447111cea2e87c50778ca7b5d7cfbf09692c7e3269
#4 DONE 0.0s

#5 [candig-ingest internal] load build context
#5 transferring context: 2.20kB done
#5 DONE 0.0s

#6 [candig-ingest  6/10] ADD ./requirements-container.txt /ingest_app/requirements-container.txt
#6 CACHED

#7 [candig-ingest  4/10] WORKDIR /ingest_app
#7 CACHED

#8 [candig-ingest  2/10] RUN useradd -rm candig -U
#8 CACHED

#9 [candig-ingest  5/10] ADD ./requirements.txt /ingest_app/requirements.txt
#9 CACHED

#10 [candig-ingest  7/10] RUN pip install -r requirements-container.txt
#10 CACHED

#11 [candig-ingest  8/10] COPY . /ingest_app
#11 CACHED

#12 [candig-ingest  9/10] RUN chmod +x ./run.sh
#12 CACHED

#13 [candig-ingest  3/10] RUN mkdir /ingest_app
#13 CACHED

#14 [candig-ingest 10/10] RUN chown -R candig:candig /ingest_app
#14 CACHED

#15 [candig-ingest] exporting to image
#15 exporting layers done
#15 writing image sha256:76edf9ee33fc4ebfdf1680869329a717db67e90b43c7091adfc2c901534e86f3 done
#15 naming to docker.io/candig/candig-ingest:1.1.0 done
#15 DONE 0.0s
echo "    finished build-candig-ingest" >> tmp/progress.txt
printf "\nOutput of compose-candig-ingest: \n" >> tmp/error.txt
echo "    started compose-candig-ingest" >> tmp/progress.txt
source setup_hosts.sh; \
        export SERVICE_NAME=candig-ingest; \
        docker compose -f lib/candigv2/docker-compose.yml -f lib/candig-ingest/docker-compose.yml --compatibility up -d 2>&1 | tee -a tmp/error.txt
IP Address is already set to: 192.168.1.170
time="2024-01-18T11:17:38-08:00" level=warning msg="Found orphan containers ([candigv2_federation_1 candigv2_opa-runner_1 candigv2_opa_1 candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1 candigv2_vault_1 candigv2_vault-runner_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container candigv2_candig-ingest_1  Creating
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/marionshadbolt/Documents/GitHub/CanDIGv2/tmp/secrets/keycloak-client-local_candig-secret
if [ -f lib/candig-ingest/candig-ingest_setup.sh ]; then \
        source lib/candig-ingest/candig-ingest_setup.sh 2>&1 | tee -a tmp/error.txt; \
        fi
>> waiting for candig-ingest to start
...
...
...
...
```

waited a long time, but never came up

**Comment by mshadbolt** [comment]
realised I was on wrong version of ingest, pulling latest and trying again

**Comment by mshadbolt** [comment]
Retried but still getting the same error about the invalid mount config

**Review by OrdiNeu — APPROVED** [review]
Code looks good, haven't tested :heavy_check_mark:

**Comment by mshadbolt** [comment]
Realised I had wrong image specified for keycloak, fixed that and now all builds correctly and all passes integration tests

Steps needed to use this version:
`make clean-all` on current develop branch
switch to daisieh/vault-setup

edit env file - Based on M1 mac
- copy the new template env file
- copy local IP address from old .env file
- change VENV_OS: VENV_OS=arm64mac
- switch keycloak version to c3genomics, ensure the KEYCLOAK_VERSION variable is uncommented
save file

`make bin-conda`
`make init-conda`
`conda activate candig`

`make build-all`

All containers come up

`make test-integration`

All tests pass

Tried the new make targets, `make stop-all`, `make start-all`, wait a few minutes for containers to start up properly then retry `make test-integration`, all tests pass.

Happy to approve this!

**Review by mshadbolt — APPROVED** [review]
All working on my local stack

**Pull request merged**
