### PR TITLE
Keycloak m1 patch

### PR DESCRIPTION
**Pull request by shaikh-rashid**

### CODE REVIEW

**Comment by SonQBChau** [comment]
Nope, doesn't work:
```
⠿ Container candigv2_keycloak_1                                                                                                                           Started 0.4s
 ⠸ keycloak The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
echo "    finished compose-keycloak" >> /Users/sonchau/Documents/GitHub/CANDIG/CanDIGv2/tmp/progress.txt
Waiting for keycloak to start
User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'
Error: No such container: 
Error: No such container: 
Error: No such container: 
Error: No such container: 
```
Docker shows incompatible:
Screenshot 2023-01-09 at 4 32 45 PM

**Comment by shaikh-rashid** [comment]
@SonQBChau can you take a look at `example.env` and your `.env` to see if they are same? `.env` needs the following change for M1 macs:

```
KEYCLOAK_VERSION=16.1.1
KEYCLOAK_BASE_IMAGE=quay.io/c3genomics/keycloak:${KEYCLOAK_VERSION}.arm64
```

**Comment by SonQBChau** [comment]
Issue resolved. I didn't know I have to uncomment the KEYCLOAK version for M1 instead of Intel based

**Review by SonQBChau — APPROVED** [review]

**Review by daisieh — APPROVED** [review]
LGTM

**Pull request merged**
