### PR TITLE
CanDIG Data Portal - Tyk and bugfixes

### PR DESCRIPTION
**Pull request by amanjeev**

### CODE REVIEW

**Comment by shaikh-rashid** [comment]
Please update `example.env` and put `candig-data-portal` before or after `cancogen-dashboard`. Also, will we still need `cancogen-dashboard` after this PR?

**Review by shaikh-rashid — APPROVED** [review]
Thank you for updating this. Conditionally marked with approval, pending change to `example.env` as requested.

**Comment by amanjeev** [comment]
ugh i had made the change but did not commit that hunk sorry, pushing now

**Review by CourtneyGosselin — APPROVED** [review]
LGTM

**Comment by amanjeev** [comment]
@shaikh-rashid Moved candig-data-portal after cancogen-dashboard.   

> Also, will we still need cancogen-dashboard after this PR?

I have no idea.  maybe @CourtneyGosselin or @haoyuanli can comment on that?

**Comment by jimmyhli** [comment]
> @shaikh-rashid Moved candig-data-portal after cancogen-dashboard.
> 
> > Also, will we still need cancogen-dashboard after this PR?
> 
> I have no idea. maybe @CourtneyGosselin or @haoyuanli can comment on that?

they serve different purposes, the candig-data-portal only has the mcode/phenopackets components so far

**Pull request merged**
