### PR TITLE
Enable data censoring and rename cancer_type to primary_site

### PR DESCRIPTION
**Pull request by OrdiNeu**
# Description
Handles renaming cancer_type to primary_site globally, and enables data censoring

## Related PRs:
- [Katsu](https://github.com/CanDIG/katsu/pull/205)
- [Query](https://github.com/CanDIG/candigv2-query/pull/40)
- [Data Portal](https://github.com/CanDIG/candig-data-portal/pull/144)

Need to do a full runbook test I think for this one, there's an unknown amount of things that can break due to this.

### CODE REVIEW

**Comment by SonQBChau** [comment]
I found 2 visual bugs on data-portal
1. Visiting completeness page has incorrect range
Screenshot 2024-05-24 at 4 13 52 PM
2. Ingest a small dataset breaks the search page Total patient
Screenshot 2024-05-24 at 4 17 30 PM

**Comment by OrdiNeu** [comment]
>     1. Visiting completeness page has incorrect range 

I can't replicate this -- which datasets were ingested for this screenshot? I do see a possible bug though, which I will fix.

>     2. Ingest a small dataset breaks the search page

Good catch, fixed in `[f31e36c](https://github.com/CanDIG/CanDIGv2/pull/613/commits/f31e36c9d698077fa26294d3800768d8548571e0)`

**Comment by mshadbolt** [comment]
I get this error message on the search page 
Screenshot 2024-05-31 at 1 45 43 PM

**Review by mshadbolt — CHANGES_REQUESTED** [review]
Overall looks good to me and seems to be functioning as expected. One bug I found is when I changed the threshold to 10 in the env file, the 'total patients' column doesn't seem to be updated to the correct threshold
Screenshot 2024-06-03 at 12 20 33 PM

**Comment by OrdiNeu** [comment]
> Overall looks good to me and seems to be functioning as expected. One bug I found is when I changed the threshold to 10 in the env file, the 'total patients' column doesn't seem to be updated to the correct threshold Screenshot 2024-06-03 at 12 20 33 PM

image

I can't seem to replicate that -- are you certain you updated both data-portal and Query when making that change?

**Review by CourtneyGosselin — APPROVED** [review]
LGTM once we got passed the red screen error. Once Marions bug is taken care of good to merge

**Review by mshadbolt — APPROVED** [review]
rebuilt and am now seeing the appropriate threshold level for total patients. LGTM!

**Pull request merged**
