### PR TITLE
DIG-1662: Disable 'red screen' errors on the data portal on production instances

### PR DESCRIPTION
**Pull request by OrdiNeu**
## Ticket(s)

- [DIG-1662](https://candig.atlassian.net/browse/DIG-1662)

## Submodule PRs

- [Data Portal #154](https://github.com/CanDIG/candig-data-portal/pull/154)

## Description

- This disables the red screen error on the data portal on production instances when `DEBUG_MODE` in your .env is not set to `1`.

## Expected Behaviour

- **Requires the corresponding commit on CanDIGv2 to work**. Add an eslint error (e.g. an empty comment). It should still show the red screen by default. If you then edit `DEBUG_MODE` in your `.env` and **rebuild** (_not_ `docker cp`, instead use `make clean-candig-data-portal; make build-candig-data-portal; make compose-candig-data-portal`), the error message should go away without fixing the eslint error.

[DIG-1662]: https://candig.atlassian.net/browse/DIG-1662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mshadbolt** [comment]
I went through the testing steps and it works as expected. What is the behaviour if the error is a runtime error that makes the portal unable to display, instead of just a linting error, e.g. opening a patient info page but the service is too busy to respond and gives back something blank, will a user just see a blank screen?

**Comment by OrdiNeu** [comment]
@mshadbolt 
> I went through the testing steps and it works as expected. What is the behaviour if the error is a runtime error that makes the portal unable to display, instead of just a linting error, e.g. opening a patient info page but the service is too busy to respond and gives back something blank, will a user just see a blank screen?

Yes, the user will just see the [white screen of death](https://www.educative.io/answers/what-is-white-screen-of-death-in-react-apps-and-how-to-fix-it), with error messages in the console.

**Comment by mshadbolt** [comment]
Is there a way we can display a sensible error message or redirect them or advise them to try refreshing/clearing cache/cookies etc?

**Comment by mshadbolt** [comment]
> Is there a way we can display a sensible error message or redirect them or advise them to try refreshing/clearing cache/cookies etc?

We decided we can address this in another ticket: https://candig.atlassian.net/browse/DIG-1679

**Review by mshadbolt — APPROVED** [review]
Works as expected based on testing instructions

**Pull request merged**
