### PR TITLE
DIG-1169, DIG-1402: Create per-service stores in Vault, use this for Opa

### PR DESCRIPTION
**Pull request by daisieh**
This is pretty complicated:

Vault now sets up the ability for each service to have its own secret store, controlled by an Approle token that is keyed to just that service's containers. For the average service, it should only need to access its own service store, and I'll discuss the exceptions in a bit.

There is a universal approle token `vault-approle-token` that is created as a secret during `make docker-secrets`. If CANDIG_DEBUG_MODE is 0, this secret is only useable by any container in the Gateway of the docker network. This is a periodic token that gets refreshed on a regular basis by the vault-runner container.

Each service that chooses to use a Vault service-store should pass in the `vault-approle-token` secret and the name of the service as the `SERVICE_NAME` env var in its docker-compose.yml file. It will then call the `create_service_store.sh <service_name>` script as part of its setup. (This is all in the template module now.) 

`create_service_store.sh` does the following:
- creates a policy and approle for the service. The approle that is created is locked to only the service's containers' IP addresses if CANDIG_DEBUG_MODE is 0. 
- creates a role id for the service's approle and puts the role id in the containers for the service, at `/home/candig/roleid`. You might see errors for containers that don't have a /home/candig directory; either ignore this or fix it, as needed.
- lets opa have access to this store (will be useful for query token etc).
- creates a key-value store at Vault for the service. 

From the point of view of the service, candig-authx does everything else, and it can call the `get_service_store_secret` and `set_service_store_secret` methods to use the store.

The exception for each service only accessing its own service is for Opa: Ingest needs to be able to add users and datasets to the access path, so we add the path `opa/access` to its policy in Vault. Likewise, federation needs to be able to update the keys for new IDPs, so we add the path `opa/data` to its policy.

I think that the modules being updated in this PR should cause all of the submodules to be connected to their right branches, but I'm not sure...go into opa, ingest, federation, and make sure that their requirements.txt files use the daisieh/vault-opa branch of candigv2-authx.

If that's all worked, make test-integration should work.

### CODE REVIEW

**Comment by mshadbolt** [comment]
I rebuilt all images using this branch, stack got up and running, I get the following 4 failing tests when doing `make integration`
```
=============================================== short test summary info ================================================
FAILED etc/tests/test_integration.py::test_add_opa_dataset - AssertionError: assert 'OPA-TEST' in []
FAILED etc/tests/test_integration.py::test_katsu_users_data_access - AssertionError: Authorized datasets missing.
FAILED etc/tests/test_integration.py::test_htsget_access_data[CANDIG_NOT_ADMIN-NA18537-True] - assert (403 == 200) == True
FAILED etc/tests/test_integration.py::test_beacon[CANDIG_NOT_ADMIN-NC_000021.8:g.5030847T>A-can_access1-cannot_access1] - assert 'multisample_1' in "{'meta': {'apiVersion': '1.0.0', 'beaconId': 'org.candig.htsget.beacon', 'receivedReques...
============================================ 4 failed, 24 passed in 35.07s ============================================= 
```

**Comment by mshadbolt** [comment]
I tried pulling latest changes and rebuilding and now have 6 failing tests
```
=============================================== short test summary info ================================================
FAILED etc/tests/test_integration.py::test_opa_datasets[CANDIG_SITE_ADMIN-SYNTHETIC-2] - AssertionError: assert 'SYNTHETIC-2' in []
FAILED etc/tests/test_integration.py::test_opa_datasets[CANDIG_NOT_ADMIN-SYNTHETIC-1] - AssertionError: assert 'SYNTHETIC-1' in []
FAILED etc/tests/test_integration.py::test_add_opa_dataset - assert 500 == 200
FAILED etc/tests/test_integration.py::test_katsu_users_data_access - AssertionError: Authorized datasets missing.
FAILED etc/tests/test_integration.py::test_htsget_access_data[CANDIG_NOT_ADMIN-NA18537-True] - assert (403 == 200) == True
FAILED etc/tests/test_integration.py::test_beacon[CANDIG_NOT_ADMIN-NC_000021.8:g.5030847T>A-can_access1-cannot_access1] - assert 'multisample_1' in "{'meta': {'apiVersion': '1.0.0', 'beaconId': 'org.candig.htsget.beacon', 'receivedReques...
============================================ 6 failed, 22 passed in 26.22s =============================================
```

**Comment by SonQBChau** [comment]
my build finished but I get some errors:
```
Error logs for vault:
--------------------
543     time="2024-01-11T12:22:37+07:00" level=warning msg="Found orphan containers ([candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
667     {"request_id":"803234de-a879-d29a-f67e-40f6a70947e9","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Supplying a custom ID for the token uses the weaker SHA1 hashing instead of the more secure SHA2-256 HMAC for token obfuscation. SHA1 hashed tokens on the wire leads to less secure lookups.","Endpoint ignored these unrecognized parameters: [periodic]"],"auth":{"client_token":"XACMY2xACnOqZ6DyRhmSjg","accessor":"lOiCtKblZnEoyiYI1dnHW7eT","policies":["approle","default"],"token_policies":["approle","default"],"metadata":null,"lease_duration":2764800,"renewable":true,"entity_id":"","token_type":"service","orphan":false,"mfa_requirement":null,"num_uses":0}}
676     Error writing data to auth/jwt/config: Error making API request.
679     Code: 400. Errors:
681     * error checking oidc discovery URL
--------------------


Error logs for tyk:
--------------------
795     time="2024-01-11T12:23:36+07:00" level=warning msg="Found orphan containers ([candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
807     {"status":"error","message":"Attempted administrative access with invalid or missing key!"}
808     {"status":"error","message":"Attempted administrative access with invalid or missing key!"}
--------------------


Error logs for opa:
--------------------
812     time="2024-01-11T12:23:42+07:00" level=warning msg="The "SERVICE_NAME" variable is not set. Defaulting to a blank string."
865     time="2024-01-11T12:23:44+07:00" level=warning msg="Found orphan containers ([candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
949     yq: Error starting jq: FileNotFoundError: [Errno 2] No such file or directory: 'jq'. Is jq installed and available on PATH?
--------------------


Error logs for federation:
--------------------
956     time="2024-01-11T12:24:02+07:00" level=warning msg="The "SERVICE_NAME" variable is not set. Defaulting to a blank string."
1014    time="2024-01-11T12:24:04+07:00" level=warning msg="Found orphan containers ([candigv2_opa-runner_1 candigv2_opa_1 candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
1094    yq: Error starting jq: FileNotFoundError: [Errno 2] No such file or directory: 'jq'. Is jq installed and available on PATH?
--------------------


Error logs for candig-ingest:
--------------------
1109    time="2024-01-11T12:24:05+07:00" level=warning msg="The "SERVICE_NAME" variable is not set. Defaulting to a blank string."
1165    time="2024-01-11T12:24:05+07:00" level=warning msg="Found orphan containers ([candigv2_federation_1 candigv2_opa-runner_1 candigv2_opa_1 candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
1245    yq: Error starting jq: FileNotFoundError: [Errno 2] No such file or directory: 'jq'. Is jq installed and available on PATH?
```
I don't think I have jq on my system, is it a prerequisite?

**Comment by daisieh** [comment]
Yes, I added it into requirements.txt, so you might want to do a new pip install -r requirements.txt. That might be the cause of some of the vault build errors.

**Comment by SonQBChau** [comment]
I've confirmed it still happened with jp installed. Maybe I need to manually add it to PATH as suggested?  Did you encounter this @mshadbolt ?

**Comment by mshadbolt** [comment]
I do remember getting these errors at some point, I am not exactly sure what fixed it but I would try re-initialising conda
```
make bin-conda
make init-conda
```
Deactivate any existing environment
```
conda deactivate
```
And ensuring the conda environment is activated before running the tests
```
conda activate candig
```
And ensure all the sub-modules are on the expected versions for this PR

My tests are passing at these versions: 
```
(candig) marionshadbolt@Marions-MacBook-Air CanDIGv2 % git submodule foreach 'git status'
Entering 'lib/candig-data-portal/candig-data-portal'
HEAD detached at fb9c83a
nothing to commit, working tree clean
Entering 'lib/candig-ingest/candigv2-ingest'
On branch daisieh/vault-opa
Your branch is behind 'origin/daisieh/vault-opa' by 11 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
Entering 'lib/federation/federation'
On branch daisieh/vault-opa
Your branch is up to date with 'origin/daisieh/vault-opa'.

nothing to commit, working tree clean
Entering 'lib/htsget/htsget_app'
HEAD detached from cd37615
nothing to commit, working tree clean
Entering 'lib/katsu/katsu_service'
HEAD detached from 445fd7eb
nothing to commit, working tree clean
Entering 'lib/opa/opa'
HEAD detached at 39d337c
nothing to commit, working tree clean
Entering 'lib/query/query'
HEAD detached at b9fa433
nothing to commit, working tree clean
Entering 'lib/toil/toil-docker'
HEAD detached at b0ff5be0
nothing to commit, working tree clean
```

**Comment by mshadbolt** [comment]
oh i just realised opa is on the wrong branch, I am going to try to rebuild and restart the stack and re-run tests

**Comment by SonQBChau** [comment]
are you using zsh or bash shell @mshadbolt ?

**Comment by mshadbolt** [comment]
zshell

**Comment by mshadbolt** [comment]
ok I tried to rebuild stack etc and now it sets up okay but am failing 21 integration tests :( not sure why it keeps breaking when I try to refresh the stack

**Comment by daisieh** [comment]
Which tests are failing?

**Comment by mshadbolt** [comment]
```
==================================================================================== short test summary info ====================================================================================
FAILED etc/tests/test_integration.py::test_tyk - assert False
FAILED etc/tests/test_integration.py::test_opa_datasets[CANDIG_SITE_ADMIN-SYNTHETIC-2] - AssertionError: assert 'SYNTHETIC-2' in []
FAILED etc/tests/test_integration.py::test_opa_datasets[CANDIG_NOT_ADMIN-SYNTHETIC-1] - AssertionError: assert 'SYNTHETIC-1' in []
FAILED etc/tests/test_integration.py::test_add_opa_dataset - assert 500 == 200
FAILED etc/tests/test_integration.py::test_site_admin[CANDIG_SITE_ADMIN-True] - AssertionError: assert ('result' in {}) == True
FAILED etc/tests/test_integration.py::test_vault - AssertionError: assert 'auth' in {'errors': ['Vault is sealed']}
FAILED etc/tests/test_integration.py::test_authorized_ingests - AssertionError: CLEAN_UP_PROGRAM Expected status code 204, but got 401.
FAILED etc/tests/test_integration.py::test_katsu_users_data_access - AssertionError: CLEAN_UP_PROGRAM Expected status code 204, but got 401.
FAILED etc/tests/test_integration.py::test_ingest_permissions - AssertionError: CLEAN_UP_PROGRAM Expected status code 204, but got 401.
FAILED etc/tests/test_integration.py::test_htsget - AssertionError: assert <ExitCode.TESTS_FAILED: 1> == <ExitCode.OK: 0>
FAILED etc/tests/test_integration.py::test_htsget_add_sample_to_dataset - KeyError: 'drsobjects'
FAILED etc/tests/test_integration.py::test_htsget_access_data[CANDIG_SITE_ADMIN-NA18537-True] - assert (403 == 200) == True
FAILED etc/tests/test_integration.py::test_htsget_access_data[CANDIG_NOT_ADMIN-NA18537-True] - assert (403 == 200) == True
FAILED etc/tests/test_integration.py::test_beacon[CANDIG_SITE_ADMIN-NC_000021.8:g.5030847T>A-can_access0-cannot_access0] - assert 'multisample_1' in "{'meta': {'apiVersion': '1.0.0', 'beaconId': 'org.candig.htsget.beacon', 'receivedRequestSummary': {'apiVersion': '1....nomicVariant', 'schema': 'ga4gh-beacon-va...
FAILED etc/tests/test_integration.py::test_beacon[CANDIG_NOT_ADMIN-NC_000021.8:g.5030847T>A-can_access1-cannot_access1] - assert 'multisample_1' in "{'meta': {'apiVersion': '1.0.0', 'beaconId': 'org.candig.htsget.beacon', 'receivedRequestSummary': {'apiVersion': '1....nomicVariant', 'schema': 'ga4gh-beacon-va...
FAILED etc/tests/test_integration.py::test_ingest_htsget - assert 403 == 200
FAILED etc/tests/test_integration.py::test_sample_metadata - AssertionError: assert 'genomes' in {'message': 'Could not find sample SAMPLE_REGISTRATION_1'}
FAILED etc/tests/test_integration.py::test_server_count - assert 0 > 0
FAILED etc/tests/test_integration.py::test_services_count - assert 0 > 0
FAILED etc/tests/test_integration.py::test_federation_call - IndexError: list index out of range
FAILED etc/tests/test_integration.py::test_add_server - IndexError: list index out of range
================================================================================= 21 failed, 7 passed in 6.04s ==================================================================================
```

**Comment by mshadbolt** [comment]
some of the recent logs from opa

```
2024-01-11 15:39:25 
2024-01-11 15:39:25 vault token not stored
2024-01-11 15:39:55 storing vault token
2024-01-11 15:39:55 secret_id: {"errors":["Vault is sealed"]}
2024-01-11 15:39:55 
2024-01-11 15:39:55 vault token not stored
```

**Comment by mshadbolt** [comment]
I think maybe the vault is staying sealed because it can't find the keys file when the container starts, each time the vaultrunner container starts I get:
```
2024-01-11 15:28:49 tail: can't open '/vault/config/keys.txt': No such file or directory
2024-01-11 15:28:49 tail: no files
```

**Comment by daisieh** [comment]
Try running make clean-vault etc and see what the output is.

**Comment by mshadbolt** [comment]
did `make clean-all` then `make build-all`

All services come up

some minor errors:
```
Error logs for minio:
--------------------
--------------------


Error logs for postgres:
--------------------
539     time="2024-01-11T16:44:01-08:00" level=warning msg="Found orphan containers ([candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for htsget:
--------------------
546     time="2024-01-11T16:44:02-08:00" level=warning msg="Found orphan containers ([candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for katsu:
--------------------
553     time="2024-01-11T16:44:02-08:00" level=warning msg="Found orphan containers ([candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for candig-data-portal:
--------------------
560     time="2024-01-11T16:44:03-08:00" level=warning msg="Found orphan containers ([candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for query:
--------------------
567     time="2024-01-11T16:44:04-08:00" level=warning msg="Found orphan containers ([candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for keycloak:
--------------------
632     time="2024-01-11T16:44:09-08:00" level=warning msg="Found orphan containers ([candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
642     WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
647     WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
652     WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
--------------------


Error logs for vault:
--------------------
931     time="2024-01-11T16:45:03-08:00" level=warning msg="Found orphan containers ([candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
1055    {"request_id":"fc430d70-40e3-3978-4f5a-f06396864a1c","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Supplying a custom ID for the token uses the weaker SHA1 hashing instead of the more secure SHA2-256 HMAC for token obfuscation. SHA1 hashed tokens on the wire leads to less secure lookups.","Endpoint ignored these unrecognized parameters: [periodic]"],"auth":{"client_token":"DzSvIW2iIKPd9sFg2Jgw","accessor":"jvfdqXs2pGyZZsNFVQ93u5s6","policies":["approle","default"],"token_policies":["approle","default"],"metadata":null,"lease_duration":2764800,"renewable":true,"entity_id":"","token_type":"service","orphan":false,"mfa_requirement":null,"num_uses":0}}
--------------------


Error logs for tyk:
--------------------
1285    time="2024-01-11T16:45:55-08:00" level=warning msg="Found orphan containers ([candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for opa:
--------------------
1302    time="2024-01-11T16:46:09-08:00" level=warning msg="The "SERVICE_NAME" variable is not set. Defaulting to a blank string."
1407    time="2024-01-11T16:46:25-08:00" level=warning msg="Found orphan containers ([candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
1614    Error response from daemon: Could not find the file /home/candig in container candigv2_opa_1
--------------------


Error logs for federation:
--------------------
1625    time="2024-01-11T16:47:16-08:00" level=warning msg="The "SERVICE_NAME" variable is not set. Defaulting to a blank string."
1684    time="2024-01-11T16:47:19-08:00" level=warning msg="Found orphan containers ([candigv2_opa-runner_1 candigv2_opa_1 candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------


Error logs for candig-ingest:
--------------------
1931    time="2024-01-11T16:47:29-08:00" level=warning msg="The "SERVICE_NAME" variable is not set. Defaulting to a blank string."
1987    time="2024-01-11T16:47:31-08:00" level=warning msg="Found orphan containers ([candigv2_federation_1 candigv2_opa-runner_1 candigv2_opa_1 candigv2_tyk_1 candigv2_tyk-redis_1 candigv2_vault_1 candigv2_vault-runner_1 candigv2_keycloak_1 candigv2_query_1 candigv2_candig-data-portal_1 candigv2_katsu_1 candigv2_htsget_1 candigv2_metadata-db_1 candigv2_minio_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
--------------------
Number of expected CanDIG services matches number of containers running! Potentially useful error log segments listed above for debugging.
```

all integration tests pass

confirming git submodule commit hashes are:
```
(candig) marionshadbolt@Marions-Air CanDIGv2 % git submodule foreach 'git status'
Entering 'lib/candig-data-portal/candig-data-portal'
HEAD detached at fb9c83a
nothing to commit, working tree clean
Entering 'lib/candig-ingest/candigv2-ingest'
HEAD detached at ad459d0
nothing to commit, working tree clean
Entering 'lib/federation/federation'
On branch daisieh/vault-opa
Your branch is up to date with 'origin/daisieh/vault-opa'.

nothing to commit, working tree clean
Entering 'lib/htsget/htsget_app'
HEAD detached from cd37615
nothing to commit, working tree clean
Entering 'lib/katsu/katsu_service'
HEAD detached from 445fd7eb
nothing to commit, working tree clean
Entering 'lib/opa/opa'
On branch daisieh/vault-opa
Your branch is up to date with 'origin/daisieh/vault-opa'.

nothing to commit, working tree clean
Entering 'lib/query/query'
HEAD detached at b9fa433
nothing to commit, working tree clean
Entering 'lib/toil/toil-docker'
HEAD detached at b0ff5be0
nothing to commit, working tree clean
```

**Comment by daisieh** [comment]
Can you take a close look at the beginning of the `compose-opa` part of the log? Line 285 of the Makefile should set the SERVICE_NAME variable:
```
	export SERVICE_NAME=$*; \
	docker compose -f lib/candigv2/docker-compose.yml -f lib/$*/docker-compose.yml --compatibility up -d 2>&1 | tee -a $(ERRORLOG)
```

**Comment by daisieh** [comment]
Okay, I think I was being deceived by those `The "SERVICE_NAME" variable is not set.` errors: they are irrelevant because they're happening during the make build step, but it's easily solved by adding `export SERVICE_NAME=$*;` to the build target as well.

**Comment by SonQBChau** [comment]
ok, I manually installed jq using brew as suggested by jq official site and I got it working. 
All built and tests passed. 
I don't know why it worked for @mshadbolt but not me, so it might be just my machine.

**Review by SonQBChau — APPROVED** [review]

**Pull request merged**
